---
- name: Install packages
  apt:
    name: "{{ _nginx_packages }}"

- name: Add modules
  lineinfile:
      path: /etc/nginx/modules-available/{{ item }}.conf
      line: load_module "modules/{{ item }}.so";
      create: yes
  with_items: "{{ nginx_modules }}"
  notify: restart-webserver

- name: Enable modules
  file:
    src: /etc/nginx/modules-available/{{ item }}.conf
    dest: /etc/nginx/modules-enabled/{{ item }}.conf
    state: link
  with_items: "{{ nginx_modules }}"
  notify: restart-webserver

- name: Add configs
  template:
    src: "{{ item.src }}"
    dest: /etc/nginx/conf.d/{{ item.name }}.conf
  with_items: "{{ nginx_configs }}"
  notify: restart-webserver

- name: Add snippets
  template:
    src: "{{ item.src }}"
    dest: /etc/nginx/snippets/{{ item.name }}.conf
  with_items: "{{ nginx_snippets }}"
  notify: restart-webserver
    
- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart-webserver

- name: Add sites
  template:
    src: "{{ item.src }}"
    dest: /etc/nginx/sites-available/{{ item.name }}.conf
  with_items: "{{ nginx_sites }}"
  notify: restart-webserver

- name: Enable sites
  file:
    src: /etc/nginx/sites-available/{{ item.name }}.conf
    dest: /etc/nginx/sites-enabled/{{ item.name }}.conf
    state: link
  with_items: "{{ nginx_sites }}"
  notify: restart-webserver

- name: Start service
  service:
    name: "{{ _nginx_service }}"
    state: started
    enabled: yes